# Generated by Django 6.0.6 on 2026-06-04 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('entity', models.CharField(max_length=50)),
                ('entity_id', models.CharField(blank=True, max_length=50)),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_no', models.CharField(max_length=30, unique=True)),
                ('loan_amount', models.BigIntegerField()),
                ('loan_purpose', models.CharField(max_length=200)),
                ('tenor', models.IntegerField()),
                ('admin_fee_type', models.CharField(choices=[('percentage', 'Persentase'), ('fixed', 'Tetap')], max_length=20)),
                ('admin_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('admin_fee_amount', models.BigIntegerField(default=0)),
                ('disbursed_amount', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Diajukan'), ('under_review', 'Sedang Direview'), ('approved', 'Disetujui'), ('rejected', 'Ditolak'), ('disbursed', 'Dicairkan')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('application_date', models.DateField()),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='employees.employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loan_applications',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_no', models.CharField(max_length=30, unique=True)),
                ('principal_amount', models.BigIntegerField()),
                ('admin_fee_type', models.CharField(choices=[('percentage', 'Persentase'), ('fixed', 'Tetap')], max_length=20)),
                ('admin_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('admin_fee_amount', models.BigIntegerField(default=0)),
                ('disbursed_amount', models.BigIntegerField(default=0)),
                ('tenor', models.IntegerField()),
                ('monthly_payment', models.BigIntegerField()),
                ('total_payment', models.BigIntegerField()),
                ('outstanding_balance', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('paid_off', 'Lunas'), ('overdue', 'Terlambat'), ('written_off', 'Hapus Buku')], default='active', max_length=20)),
                ('disbursement_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='employees.employee')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='loan', to='loans.loanapplication')),
            ],
            options={
                'db_table': 'loans',
            },
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_no', models.CharField(max_length=30, unique=True)),
                ('amount', models.BigIntegerField()),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('auto_debit', 'Auto Debit'), ('bank_transfer', 'Transfer Bank'), ('cash', 'Tunai')], max_length=20)),
                ('reference_no', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Dikonfirmasi'), ('rejected', 'Ditolak')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='loans.loan')),
            ],
            options={
                'db_table': 'loan_payments',
            },
        ),
        migrations.CreateModel(
            name='LoanSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_amount', models.BigIntegerField(default=0)),
                ('remaining_principal', models.BigIntegerField(default=0)),
                ('penalty', models.BigIntegerField(default=0)),
                ('settlement_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('auto_debit', 'Auto Debit'), ('bank_transfer', 'Transfer Bank'), ('cash', 'Tunai')], max_length=20)),
                ('reference_no', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Selesai')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settlement', to='loans.loan')),
            ],
            options={
                'db_table': 'loan_settlements',
            },
        ),
        migrations.CreateModel(
            name='LoanInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_no', models.IntegerField()),
                ('due_date', models.DateField()),
                ('amount', models.BigIntegerField()),
                ('remaining_balance', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('unpaid', 'Belum Bayar'), ('paid', 'Lunas'), ('overdue', 'Terlambat'), ('waived', 'Dibebaskan')], default='unpaid', max_length=20)),
                ('paid_amount', models.BigIntegerField(default=0)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='loans.loan')),
            ],
            options={
                'db_table': 'loan_installments',
                'unique_together': {('loan', 'installment_no')},
            },
        ),
    ]
