# Generated by Django 6.0.6 on 2026-06-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loansettlement',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='settlements/proofs/'),
        ),
    ]
