# Generated by Django 6.0.6 on 2026-06-06 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_add_proof_image_to_settlement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loansettlement',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='loans.loan'),
        ),
    ]
