# Generated by Django 6.0.6 on 2026-06-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_settlement_fk_allow_resubmit'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='id_card_document',
            field=models.FileField(blank=True, null=True, upload_to='applications/documents/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='ktp_document',
            field=models.FileField(blank=True, null=True, upload_to='applications/documents/'),
        ),
    ]
