# Generated by Django 6.0.6 on 2026-06-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loanapplication_id_card_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Diajukan'), ('under_review', 'Sedang Direview'), ('verified', 'Terverifikasi'), ('approved', 'Disetujui'), ('rejected', 'Ditolak'), ('disbursed', 'Dicairkan')], default='draft', max_length=20),
        ),
    ]
