# Generated by Django 6.0.6 on 2026-06-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_alter_loanapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanpayment',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='payments/proofs/'),
        ),
    ]
