# Generated by Django 6.0.6 on 2026-06-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_rename_ktp_document_to_signature_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanpayment',
            options={'ordering': ['-payment_date', '-created_at']},
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='admin_fee_type',
            field=models.CharField(choices=[('percentage', 'Persentase'), ('fixed', 'Tetap'), ('tiered', 'Berjenjang')], max_length=20),
        ),
    ]
