# Generated by Django 6.0.6 on 2026-06-04 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('mou_number', models.CharField(max_length=50, unique=True)),
                ('mou_date', models.DateField()),
                ('mou_expiry_date', models.DateField()),
                ('max_loan_amount', models.BigIntegerField(default=0)),
                ('max_loan_to_salary_percent', models.DecimalField(decimal_places=2, default=75, max_digits=5)),
                ('admin_fee_type', models.CharField(choices=[('percentage', 'Persentase'), ('fixed', 'Tetap')], default='percentage', max_length=20)),
                ('admin_fee', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('max_tenor', models.IntegerField(default=12)),
                ('max_active_loans', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('inactive', 'Tidak Aktif')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('birth_place', models.CharField(blank=True, max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('department', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('employment_status', models.CharField(choices=[('tetap', 'Tetap'), ('kontrak', 'Kontrak'), ('probasi', 'Probasi')], max_length=20)),
                ('marital_status', models.CharField(blank=True, choices=[('belum_menikah', 'Belum Menikah'), ('menikah', 'Menikah'), ('cerai', 'Cerai')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('join_date', models.DateField()),
                ('salary', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('resigned', 'Resign'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.company')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
    ]
