# Generated by Django 6.0.6 on 2026-06-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Aktif'), ('inactive', 'Tidak Aktif'), ('resigned', 'Resign')], default='active', max_length=20),
        ),
    ]
