# Generated by Django 6.0.6 on 2026-06-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_account_name_employee_account_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_admin_fee_type', models.CharField(choices=[('percentage', 'Persentase'), ('fixed', 'Tetap')], default='percentage', max_length=20)),
                ('default_admin_fee', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('max_loan_amount', models.BigIntegerField(default=50000000)),
                ('min_loan_amount', models.BigIntegerField(default=1000000)),
                ('max_tenor', models.IntegerField(default=36)),
                ('min_tenor', models.IntegerField(default=3)),
                ('early_settlement_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('auto_debit_enabled', models.BooleanField(default=True)),
                ('email_notification', models.BooleanField(default=True)),
                ('overdue_reminder', models.BooleanField(default=True)),
                ('payment_confirmation', models.BooleanField(default=True)),
                ('loan_approval', models.BooleanField(default=True)),
                ('disbursement_notice', models.BooleanField(default=True)),
                ('company_name', models.CharField(default='DANAKARYA', max_length=150)),
                ('company_tagline', models.CharField(default='Dana & Nabung untuk Karyawan Sejahtera', max_length=200)),
                ('currency', models.CharField(choices=[('IDR', 'IDR - Rupiah Indonesia'), ('USD', 'USD - US Dollar')], default='IDR', max_length=10)),
                ('date_format', models.CharField(choices=[('dd/MM/yyyy', 'DD/MM/YYYY'), ('MM/dd/yyyy', 'MM/DD/YYYY'), ('yyyy-MM-dd', 'YYYY-MM-DD')], default='dd/MM/yyyy', max_length=20)),
                ('timezone', models.CharField(choices=[('Asia/Jakarta', 'WIB (UTC+7)'), ('Asia/Makassar', 'WITA (UTC+8)'), ('Asia/Jayapura', 'WIT (UTC+9)')], default='Asia/Jakarta', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'system settings',
                'db_table': 'system_settings',
            },
        ),
    ]
