# Generated by Django 6.0.6 on 2026-06-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_systemsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='admin_fee_type',
            field=models.CharField(choices=[('percentage', 'Persentase'), ('fixed', 'Tetap'), ('tiered', 'Berjenjang')], default='percentage', max_length=20),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='default_admin_fee_type',
            field=models.CharField(choices=[('percentage', 'Persentase'), ('fixed', 'Tetap'), ('tiered', 'Berjenjang')], default='tiered', max_length=20),
        ),
    ]
