# Generated by Django 6.0.6 on 2026-06-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_company_admin_fee_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='admin_fee_tier1_amount',
            field=models.BigIntegerField(default=50000),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='admin_fee_tier1_max',
            field=models.BigIntegerField(default=1000000),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='admin_fee_tier2_amount',
            field=models.BigIntegerField(default=100000),
        ),
    ]
